# Generated by Django 4.1.3 on 2022-12-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('artista', models.CharField(max_length=60)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='guitarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=60)),
                ('instrumento', models.CharField(max_length=60)),
                ('dicta', models.BooleanField()),
            ],
        ),
    ]
