# Generated by Django 4.1.3 on 2022-12-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecciones',
            name='instrumento',
            field=models.IntegerField(),
        ),
    ]
