# Generated by Django 4.1.3 on 2022-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_alter_lecciones_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecciones',
            name='instrumento',
            field=models.CharField(max_length=60),
        ),
    ]
