# Generated by Django 4.1.3 on 2022-12-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_alter_lecciones_instrumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitarras',
            old_name='marca',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='guitarras',
            name='disponibilidad',
        ),
    ]
