# Generated by Django 4.1.3 on 2022-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0004_rename_marca_guitarras_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecciones',
            name='dicta',
            field=models.BooleanField(default=False),
        ),
    ]
